# Generated by Django 4.1.2 on 2022-11-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_id', models.IntegerField()),
                ('text', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
    ]
