# Generated by Django 4.1.4 on 2022-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Название курса')),
                ('description', models.CharField(max_length=100, verbose_name='Описание курса')),
                ('category', models.CharField(max_length=30, verbose_name='Категория курса')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('price', models.IntegerField(verbose_name='Цена курса')),
                ('rate', models.CharField(max_length=20, verbose_name='Рейтинг курса')),
                ('count', models.IntegerField(verbose_name='Количество оценок')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(verbose_name='ID пользователя, купившего курс')),
                ('id_curse', models.IntegerField(verbose_name='ID курса, который купил пользователь')),
                ('date_purchase', models.DateField(auto_now=True, verbose_name='Дата покупки')),
                ('sum', models.IntegerField(verbose_name='Сумма покупки')),
                ('status', models.CharField(default='Куплен', max_length=20, verbose_name='Статус')),
                ('date_status', models.DateField(auto_now=True, verbose_name='Время статуса')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Никнейм')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
