# Generated by Django 4.1.4 on 2022-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_status',
            field=models.DateField(default='', null=True, verbose_name='Время статуса'),
        ),
    ]
