# Generated by Django 4.1.4 on 2022-12-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
