# Generated by Django 4.1.3 on 2022-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emal',
            new_name='email',
        ),
    ]
