# Generated by Django 4.1.3 on 2022-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_rename_emal_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='rate',
            field=models.CharField(max_length=20, verbose_name='Рейтинг курса'),
        ),
    ]
