# Generated by Django 4.1.4 on 2022-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_alter_purchase_date_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_status',
            field=models.DateField(default='2006-10-25', null=True, verbose_name='Время статуса'),
        ),
    ]
