# Generated by Django 4.1.4 on 2022-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.DateField(auto_now=True, verbose_name='Дата покупки'),
        ),
    ]
