# Generated by Django 4.1.3 on 2022-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0004_alter_curses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Картинка'),
        ),
    ]
