# Generated by Django 4.1.3 on 2022-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0005_alter_curses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
    ]
